Data Encoding >> Converting Categorical columns into numeric
-> Nominal / OHE
-> Label and ordinal Encoding
->Target guided ordinal encoding

In [1]:
# Nominal / OHE >> Binary vector for each of the cateories
#example single, married,separated
#single : [1,0,0]
#married:[0,1,0]
#separated : [0,0,1]

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df=pd.DataFrame({"status": ["Single","married","separated","Single","married"]})

In [3]:
df

      status
0     Single
1    married
2  separated
3     Single
4    married

In [4]:
encoder=OneHotEncoder()

In [5]:
encoder

OneHotEncoder()

In [6]:
encoded=encoder.fit_transform(df[['status']]).toarray()

In [7]:
encoded

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [8]:
encoder.get_feature_names_out()

array(['status_Single', 'status_married', 'status_separated'],
      dtype=object)

In [9]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [10]:
encoder_df

   status_Single  status_married  status_separated
0            1.0             0.0               0.0
1            0.0             1.0               0.0
2            0.0             0.0               1.0
3            1.0             0.0               0.0
4            0.0             1.0               0.0

In [11]:
encoder.transform([['Single']]).toarray()

C:\Users\Win\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [12]:
# The same thing we can do with function --> pd.get_dummies()

In [13]:
pd.concat([df,encoder_df],axis=1)

      status  status_Single  status_married  status_separated
0     Single            1.0             0.0               0.0
1    married            0.0             1.0               0.0
2  separated            0.0             0.0               1.0
3     Single            1.0             0.0               0.0
4    married            0.0             1.0               0.0

Label encoding >> Assign unique label to the categories
Using map or using library

In [14]:
df

      status
0     Single
1    married
2  separated
3     Single
4    married

In [15]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [16]:
label_encoder

LabelEncoder()

In [17]:
label_encoder.fit_transform(df[['status']])

C:\Users\Win\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 1, 2, 0, 1])

In [18]:
label_encoder.fit_transform([['seprated']])

C:\Users\Win\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0])

Ordinal encoding

high school : 1
gradiate :2 
post graduate : 3
#phd : 4

In [34]:
from sklearn.preprocessing import OrdinalEncoder
df=pd.DataFrame({'qualification': ['HS','GR','PG','PHD','HS','PHD']})

In [35]:
df

  qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5           PHD

In [36]:
encoder=OrdinalEncoder(categories=[['HS','GR','PG','PHD']])

In [37]:
encoder

OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PHD']])

In [38]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [40]:
encoder.transform([['PG']])

C:\Users\Win\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

Target Guided ordinal encoding
Relationship with target variable
A lot of unique categories
Replace the Category with mean and median if respective group

In [43]:
df=pd.DataFrame ({'time': ['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch','breakfast','dinner'],
    'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189 ]})

In [44]:
df

        time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [47]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [48]:
df['time_encoded']=df['time'].map(mean_price)

In [49]:
df

        time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333